### ISSUE TITLE
프로젝트 초기 디렉토리 구성 및 환경 설정 (Swagger, 에러/동기 핸들러 추가)

### ISSUE THREAD

**Issue by chan000518** [POM-Peace-of-memory/backend#1]
### To-do:
- [x] **프로젝트 기본 설정**  
  - 기본적인 Node.js 프로젝트 초기화 (`package.json` 생성, 필요 패키지 설치)

- [x] **디렉토리 구조 설계 및 생성**  
  - `src/` 디렉토리 생성
  - 하위 디렉토리 설정 (`config/`, `controllers/`, `middlewares/`, `routes/`, `models/`)

- [x] **Swagger 설정 및 API 문서화**  
  - Swagger 패키지 설치
  - Swagger 설정 파일 생성 및 API 문서화 준비

- [x] **에러 핸들러 구현**  
  - 에러 핸들러 작성 

- [x] **동기 핸들러 추가**  
  - 비동기 함수에서 발생하는 에러를 처리하는 핸들러 추가
